package pe.grupobbva.muro.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aviso generated by hbm2java
 */
@Entity
@Table(name = "AVISO")
public class Aviso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1088034380020176287L;
	
	private Integer idaviso;
	private String titulo;
	private String circular;
	private Date descripcion;
	private String fechacreacion;
	private Character estado;

	public Aviso() {
	}

	public Aviso(Integer idaviso) {
		this.idaviso = idaviso;
	}

	public Aviso(Integer idaviso, String titulo, String circular,
			Date descripcion, String fechacreacion, Character estado) {
		this.idaviso = idaviso;
		this.titulo = titulo;
		this.circular = circular;
		this.descripcion = descripcion;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
	}

	@Id
	@Column(name = "IDAVISO", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIdaviso() {
		return this.idaviso;
	}

	public void setIdaviso(Integer idaviso) {
		this.idaviso = idaviso;
	}

	@Column(name = "TITULO", length = 200)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "CIRCULAR", length = 400)
	public String getCircular() {
		return this.circular;
	}

	public void setCircular(String circular) {
		this.circular = circular;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DESCRIPCION", length = 7)
	public Date getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Date descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "FECHACREACION", length = 20)
	public String getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(String fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
