package pe.grupobbva.muro.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NotariaContrato generated by hbm2java
 */
@Entity
@Table(name = "NOTARIA_CONTRATO")
public class NotariaContrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7161720733418547356L;
	
	private NotariaContratoId id;
	private Contrato contrato;
	private Notaria notaria;

	public NotariaContrato() {
	}

	public NotariaContrato(NotariaContratoId id) {
		this.id = id;
	}

	public NotariaContrato(NotariaContratoId id, Contrato contrato,
			Notaria notaria) {
		this.id = id;
		this.contrato = contrato;
		this.notaria = notaria;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idnotaria", column = @Column(name = "IDNOTARIA", precision = 22, scale = 0)),
			@AttributeOverride(name = "idcontrato", column = @Column(name = "IDCONTRATO", precision = 22, scale = 0)) })
	public NotariaContratoId getId() {
		return this.id;
	}

	public void setId(NotariaContratoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCONTRATO", insertable = false, updatable = false)
	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDNOTARIA", insertable = false, updatable = false)
	public Notaria getNotaria() {
		return this.notaria;
	}

	public void setNotaria(Notaria notaria) {
		this.notaria = notaria;
	}

}
