package pe.grupobbva.muro.entity;

// Generated Feb 27, 2014 5:00:05 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransaccionDetalle generated by hbm2java
 */
@Entity
@Table(name = "TRANSACCION_DETALLE")
public class TransaccionDetalle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1732986379212737894L;
	
	private Integer iddetalle;
	private Transaccion transaccion;
	private Integer posicionx;
	private Integer posiciony;
	private Integer colspan;
	private Integer rowspan;
	private String contenido;
	private Date fechacreacion;
	private Character estado;

	public TransaccionDetalle() {
	}

	public TransaccionDetalle(Integer iddetalle) {
		this.iddetalle = iddetalle;
	}

	public TransaccionDetalle(Integer iddetalle, Transaccion transaccion,
			Integer posicionx, Integer posiciony, Integer colspan,
			Integer rowspan, String contenido, Date fechacreacion,
			Character estado) {
		this.iddetalle = iddetalle;
		this.transaccion = transaccion;
		this.posicionx = posicionx;
		this.posiciony = posiciony;
		this.colspan = colspan;
		this.rowspan = rowspan;
		this.contenido = contenido;
		this.fechacreacion = fechacreacion;
		this.estado = estado;
	}

	@Id
	@Column(name = "IDDETALLE", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getIddetalle() {
		return this.iddetalle;
	}

	public void setIddetalle(Integer iddetalle) {
		this.iddetalle = iddetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDTRANSACCION")
	public Transaccion getTransaccion() {
		return this.transaccion;
	}

	public void setTransaccion(Transaccion transaccion) {
		this.transaccion = transaccion;
	}

	@Column(name = "POSICIONX", precision = 22, scale = 0)
	public Integer getPosicionx() {
		return this.posicionx;
	}

	public void setPosicionx(Integer posicionx) {
		this.posicionx = posicionx;
	}

	@Column(name = "POSICIONY", precision = 22, scale = 0)
	public Integer getPosiciony() {
		return this.posiciony;
	}

	public void setPosiciony(Integer posiciony) {
		this.posiciony = posiciony;
	}

	@Column(name = "COLSPAN", precision = 22, scale = 0)
	public Integer getColspan() {
		return this.colspan;
	}

	public void setColspan(Integer colspan) {
		this.colspan = colspan;
	}

	@Column(name = "ROWSPAN", precision = 22, scale = 0)
	public Integer getRowspan() {
		return this.rowspan;
	}

	public void setRowspan(Integer rowspan) {
		this.rowspan = rowspan;
	}

	@Column(name = "CONTENIDO", length = 4000)
	public String getContenido() {
		return this.contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHACREACION", length = 7)
	public Date getFechacreacion() {
		return this.fechacreacion;
	}

	public void setFechacreacion(Date fechacreacion) {
		this.fechacreacion = fechacreacion;
	}

	@Column(name = "ESTADO", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

}
